[app]
LogPath = /var/log/falahos/
LogSaveName = falahos
LogFileExt = log
DBPath = /var/lib/falahos
ShellPath = /usr/share/falahos/shell
UserDataPath = /var/lib/falahos/conf

[server]
RunMode = release
ServerApi = https://api.falah-consultancy.ltd/api

[common]
RuntimePath = /var/run/casaos
