[app]
LogPath = /var/log/casaos/
LogSaveName = falahos
LogFileExt = log
DBPath = /var/lib/casaos
ShellPath = /usr/share/casaos/shell
UserDataPath = /var/lib/casaos/conf

[server]
RunMode = release
ServerApi = https://api.casaos.io/casaos-api

[common]
RuntimePath = /var/run/casaos
