// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for SetZerotierNetworkStatusJSONBodyStatus.
const (
	Offline SetZerotierNetworkStatusJSONBodyStatus = "offline"
	Online  SetZerotierNetworkStatusJSONBodyStatus = "online"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// HealthPorts defines model for HealthPorts.
type HealthPorts struct {
	TCP *[]int `json:"tcp,omitempty"`
	UDP *[]int `json:"udp,omitempty"`
}

// HealthServices defines model for HealthServices.
type HealthServices struct {
	NotRunning *[]string `json:"not_running,omitempty"`
	Running    *[]string `json:"running,omitempty"`
}

// SuccessResponseString defines model for SuccessResponseString.
type SuccessResponseString struct {
	// Data When the interface returns success, this field is the specific success information
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ZTInfo defines model for ZTInfo.
type ZTInfo struct {
	Id     *string `json:"id,omitempty"`
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// GetHealthPortsOK defines model for GetHealthPortsOK.
type GetHealthPortsOK struct {
	Data *HealthPorts `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetHealthServicesOK defines model for GetHealthServicesOK.
type GetHealthServicesOK struct {
	Data *HealthServices `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GetZTInfoOK defines model for GetZTInfoOK.
type GetZTInfoOK = ZTInfo

// ResponseClientError defines model for ResponseClientError.
type ResponseClientError = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseStringOK defines model for ResponseStringOK.
type ResponseStringOK = SuccessResponseString

// CheckUploadChunkParams defines parameters for CheckUploadChunk.
type CheckUploadChunkParams struct {
	// Path File path
	Path string `form:"path" json:"path"`

	// RelativePath File path
	RelativePath string `form:"relativePath" json:"relativePath"`

	// Filename File name
	Filename string `form:"filename" json:"filename"`

	// ChunkNumber chunk number
	ChunkNumber string `form:"chunkNumber" json:"chunkNumber"`

	// TotalChunks total chunks
	TotalChunks int `form:"totalChunks" json:"totalChunks"`
}

// PostUploadFileMultipartBody defines parameters for PostUploadFile.
type PostUploadFileMultipartBody struct {
	ChunkNumber      *string             `json:"chunkNumber,omitempty"`
	ChunkSize        *string             `json:"chunkSize,omitempty"`
	CurrentChunkSize *string             `json:"currentChunkSize,omitempty"`
	File             *openapi_types.File `json:"file,omitempty"`
	Filename         *string             `json:"filename,omitempty"`
	Identifier       *string             `json:"identifier,omitempty"`
	Path             *string             `json:"path,omitempty"`
	RelativePath     *string             `json:"relativePath,omitempty"`
	TotalChunks      *string             `json:"totalChunks,omitempty"`
	TotalSize        *string             `json:"totalSize,omitempty"`
}

// SetZerotierNetworkStatusJSONBody defines parameters for SetZerotierNetworkStatus.
type SetZerotierNetworkStatusJSONBody struct {
	Status *SetZerotierNetworkStatusJSONBodyStatus `json:"status,omitempty"`
}

// SetZerotierNetworkStatusJSONBodyStatus defines parameters for SetZerotierNetworkStatus.
type SetZerotierNetworkStatusJSONBodyStatus string

// PostUploadFileMultipartRequestBody defines body for PostUploadFile for multipart/form-data ContentType.
type PostUploadFileMultipartRequestBody PostUploadFileMultipartBody

// SetZerotierNetworkStatusJSONRequestBody defines body for SetZerotierNetworkStatus for application/json ContentType.
type SetZerotierNetworkStatusJSONRequestBody SetZerotierNetworkStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Test file methods
	// (GET /file/test)
	GetFileTest(ctx echo.Context) error
	// Check upload chunk
	// (GET /file/upload)
	CheckUploadChunk(ctx echo.Context, params CheckUploadChunkParams) error
	// Upload file
	// (POST /file/upload)
	PostUploadFile(ctx echo.Context) error
	// Get log
	// (GET /health/logs)
	GetHealthlogs(ctx echo.Context) error
	// Get port in use
	// (GET /health/ports)
	GetHealthPorts(ctx echo.Context) error
	// Get service status
	// (GET /health/services)
	GetHealthServices(ctx echo.Context) error
	// Get Zerotier info
	// (GET /zt/info)
	GetZerotierInfo(ctx echo.Context) error
	// Set Zerotier network status
	// (PUT /zt/{network_id}/status)
	SetZerotierNetworkStatus(ctx echo.Context, networkId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetFileTest converts echo context to params.
func (w *ServerInterfaceWrapper) GetFileTest(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFileTest(ctx)
	return err
}

// CheckUploadChunk converts echo context to params.
func (w *ServerInterfaceWrapper) CheckUploadChunk(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params CheckUploadChunkParams
	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameter("form", true, true, "path", ctx.QueryParams(), &params.Path)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter path: %s", err))
	}

	// ------------- Required query parameter "relativePath" -------------

	err = runtime.BindQueryParameter("form", true, true, "relativePath", ctx.QueryParams(), &params.RelativePath)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter relativePath: %s", err))
	}

	// ------------- Required query parameter "filename" -------------

	err = runtime.BindQueryParameter("form", true, true, "filename", ctx.QueryParams(), &params.Filename)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filename: %s", err))
	}

	// ------------- Required query parameter "chunkNumber" -------------

	err = runtime.BindQueryParameter("form", true, true, "chunkNumber", ctx.QueryParams(), &params.ChunkNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chunkNumber: %s", err))
	}

	// ------------- Required query parameter "totalChunks" -------------

	err = runtime.BindQueryParameter("form", true, true, "totalChunks", ctx.QueryParams(), &params.TotalChunks)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter totalChunks: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckUploadChunk(ctx, params)
	return err
}

// PostUploadFile converts echo context to params.
func (w *ServerInterfaceWrapper) PostUploadFile(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUploadFile(ctx)
	return err
}

// GetHealthlogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthlogs(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthlogs(ctx)
	return err
}

// GetHealthPorts converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthPorts(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthPorts(ctx)
	return err
}

// GetHealthServices converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthServices(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetHealthServices(ctx)
	return err
}

// GetZerotierInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetZerotierInfo(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetZerotierInfo(ctx)
	return err
}

// SetZerotierNetworkStatus converts echo context to params.
func (w *ServerInterfaceWrapper) SetZerotierNetworkStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "network_id" -------------
	var networkId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "network_id", runtime.ParamLocationPath, ctx.Param("network_id"), &networkId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter network_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetZerotierNetworkStatus(ctx, networkId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/file/test", wrapper.GetFileTest)
	router.GET(baseURL+"/file/upload", wrapper.CheckUploadChunk)
	router.POST(baseURL+"/file/upload", wrapper.PostUploadFile)
	router.GET(baseURL+"/health/logs", wrapper.GetHealthlogs)
	router.GET(baseURL+"/health/ports", wrapper.GetHealthPorts)
	router.GET(baseURL+"/health/services", wrapper.GetHealthServices)
	router.GET(baseURL+"/zt/info", wrapper.GetZerotierInfo)
	router.PUT(baseURL+"/zt/:network_id/status", wrapper.SetZerotierNetworkStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYbXPbuPH/Khj8/y+SDi0qdtKmmrkXjtPkPJmePbVvrnO2xgeBSxExCTDYpR3Fo+/e",
	"AUBKpEj5IZHbTl/ZIhe7v/3tAxd7x6UpSqNBE/LJHbeApdEI/sdHoJ9B5JSdGkt48sk9k0YTaHL/irLM",
	"lRSkjI4/o9HuGcoMCuHf5vlJyicXd/z/LaR8wv8vXpuKgxzG7wTCP2qbfBnd8dKaEiypgCAR5JXdp6IF",
	"kS+Xy+lyuYx4AiitKh02PuEnn/gyWrtzBvZGSfgv96hB+aBTv58f69Q80Zn77AeFfKvNxr2jXIGmv1lr",
	"7M5sd+nrIwg2WTDawnKsCawWuWMN7L8XU2ObBeN9cDuMzUNYuhE6I6v0fIfmzyopAbGrfxuOZVRr9Znf",
	"QT7ZrIsCEMXcv+gqql8wC1RZDQmbLRgGnlElwFTKKAMLTCETesEjDl9FUebAJ5xH3IJITnS+4BOyFUSc",
	"FqV7gy3g7QbSw0WydH8UQeF/r5S/Ha+UKU0wBx/x+omwVjgoX/fmZk+Lwj07Pzp1ElWyReGbgycq/PX9",
	"aduBVb/o+aANXdlKa+fxoGmeilxkBkcYdPAeTxtAlhF/lMK9uSC4FYvHK3b+DCfZrjtwN81+y0C7RGKO",
	"e5sK2WQcMgxwIkaZQpYqyBOXbE4YS5AqVbKRYUqnxha+svhAsk2XEa+7ay9KKulS+Gr/4PWbP//l7V/H",
	"Q6yFHGjLf3CUs5OzIWkkQdVGiIzOlYYhlO4AyMoqWpw5TgM+4T28InMNvmEoR1sGIgHLGzz8sKLMWPVt",
	"gwFRqk9QR1fV3nf5v6zG4wNZKkmVBf8DLjVjjIUXaCorgRWQKPHTJX9RWkjB4p40ubF7PvIwYYmw1y8v",
	"OUMrEeinS54RlTiJYytuR3NFWTWrEGzdCUfSFPGxhN8ykcM5yCzOzdzEhVA6rvO3+Xs1E1qDvXIGrrSa",
	"Z3T1djwuv45KPb/k3ws3d4qeFS/dKm/kapZXcD9kVcyZyB2IJpECsP8EqoAo3siGS90gY4enx6y05kYl",
	"gKxQKCHPhQZTISuAMpMgS41liUpTsG5eQAlaWGVw5PUYyxRiBe6TkbBEoawQldEYsTIHgcBuFCryNX7x",
	"UdHP1YxZKA0qMnYxfdEwEtjoU9AAfcmMZZ+N0uzCVJa9VyiNTdbnk/BgNJ/H1/rL4Wz2bgb/fDm69KWj",
	"qFPXzmke8RuwGErmZt+VtilBi1LxCT8YjUcHPOKloMxXbJyqHGIC9B/9OVC/7M4BiTmxhrcR9yqtL+Dj",
	"hE/chPlBOb+Q/Pe0dUHYH4+3DQwrubg1BC0j/uYpR4aGOt+dqqIQdjGE3xEn5sgnF/xD+/HUnQuEVGVu",
	"RLKVkqMM5HU9VgTVs9zIa5YJZDMAzcJ5SNgLDZAgI8NmwAqTqFRBwnJBYF/2aPRqf/VHj7JKX/tAWVEA",
	"gUX/TevC8OhdKDsTTfz+8PzQh3SUmzmPQhf+UoFdrJtwfcrCl0pZSJrRZz3hbXb8aIfGLeSC1A2c7gaE",
	"19oG8YB5F7D6zA+Yli5CTFfFzH/cVtZfDRv14r800j9glwyJnHl12La7P2zXix810g/aXY2Vy+mPFPLq",
	"UrGM+OunHGzfF3ffCkLdhuIMFG70Au6mr9LgQM2HuvTV3ivcU4MU3n8Irx3PgPTOJIuNe1VR5aRKYSl2",
	"U+BeM2muA9Gd+Npp0xnN9gdHPi9+pr5tzH2vxvuvB8Ur6z59R0875SmY3PEwxvIJnyktfM4NivbH0HWT",
	"2K/LtHdQJaDJNcsNt1ul3Tvjm1Hf0JBopwNtwbbNTLuiuiHZKv1YbtdXHTP7DJLqSft/rg67tbRRgO4j",
	"nPnrqhsTsfUR7g0d4VbrpYZZ2rLQMJKA9pAsiKJbfQ/m9LZ1yo4Z+gjE6vyr2Qm+bgwrNU9ls5i4n6iw",
	"v/iefOqteZ/HY+cHU5pVCI/0HFsbjcFRzamt9xAsXHGZSRkImbE/mg3En/5gtZ7B0XZjd/JD/LX2ys9D",
	"Ye1I7etDLH6juLlrb2Xvd7CGFFi/uBgkqJHwS4vvpGe1oX4eWjpOtFhZPe/xcqeBbo29vlLJMl4vR8pq",
	"gKaztoX6XB2BPmFna8J+CaJnTazunfYbvSpp5tp6+q4nvTXeJw2Y0/umlfu3wN1RpbVA0lXhyF2tj0ya",
	"+v+m0WOWS7v6CD5vVt0T8wfyq7U782Hubs0upi4kYX0d0qCyuRtMbvabJQl3ErWF3m09A1xdaZmw4Jpp",
	"4i6g0g+/7sYaeqffa6xbonvRWZ641wLRSCUIkqax4IitU26jp/QvK+dOaeuOzUSem1u2MJVD5PeoQhK7",
	"VZT5aaBZtliQZKwCZEZ3keECCYrRGkPnCu+I+bpHYv7RmqoM/NRyf+9d/nsdcbr8VwAAAP//xjYow+wc",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
