// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	types "github.com/compose-spec/compose-go/types"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	api "github.com/docker/compose/v2/pkg/api"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for Scheme.
const (
	Http  Scheme = "http"
	Https Scheme = "https"
)

// Defines values for StoreAppAuthorType.
const (
	ByFalahos StoreAppAuthorType = "by_falahos"
	Community StoreAppAuthorType = "community"
	Official  StoreAppAuthorType = "official"
	Unknown   StoreAppAuthorType = "unknown"
)

// Defines values for UpgradableAppInfoStatus.
const (
	Idle     UpgradableAppInfoStatus = "idle"
	Updating UpgradableAppInfoStatus = "updating"
)

// Defines values for WebAppGridItemAppType.
const (
	Container WebAppGridItemAppType = "container"
	Link      WebAppGridItemAppType = "link"
	V1app     WebAppGridItemAppType = "v1app"
	V2app     WebAppGridItemAppType = "v2app"
)

// Defines values for RequestComposeAppStatus.
const (
	RequestComposeAppStatusRestart RequestComposeAppStatus = "restart"
	RequestComposeAppStatusStart   RequestComposeAppStatus = "start"
	RequestComposeAppStatusStop    RequestComposeAppStatus = "stop"
)

// Defines values for SetComposeAppStatusJSONBody.
const (
	SetComposeAppStatusJSONBodyRestart SetComposeAppStatusJSONBody = "restart"
	SetComposeAppStatusJSONBodyStart   SetComposeAppStatusJSONBody = "start"
	SetComposeAppStatusJSONBodyStop    SetComposeAppStatusJSONBody = "stop"
)

// Defines values for ConvertParamsType.
const (
	Appfile ConvertParamsType = "appfile"
)

// AppStoreInfo > Do not mistake it as *information of AppStore* which does not exist.
type AppStoreInfo struct {
	Devices []DeviceStoreInfo `json:"devices" yaml:",omitempty"`
	Envs    []EnvStoreInfo    `json:"envs" yaml:",omitempty"`
	Image   string            `json:"image"`
	Ports   []PortStoreInfo   `json:"ports" yaml:",omitempty"`
	Volumes []VolumeStoreInfo `json:"volumes" yaml:",omitempty"`
}

// AppStoreMetadata defines model for AppStoreMetadata.
type AppStoreMetadata struct {
	ID        *int    `json:"id,omitempty"`
	StoreRoot *string `json:"store_root,omitempty"`
	URL       *string `json:"url,omitempty"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// CategoryInfo defines model for CategoryInfo.
type CategoryInfo struct {
	Count       *int    `json:"count,omitempty"`
	Description *string `json:"description,omitempty"`
	Font        *string `json:"font,omitempty"`
	ID          *int    `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// ComposeApp See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
type ComposeApp = types.Project

// ComposeAppContainers Schema for `ComposeAppContainersOK` response.
type ComposeAppContainers struct {
	Containers *map[string]ContainerSummary `json:"containers,omitempty"`
	Main       *string                      `json:"main,omitempty"`
}

// ComposeAppStoreInfo defines model for ComposeAppStoreInfo.
type ComposeAppStoreInfo struct {
	// Apps The key is the name of a container app, and the value is the StoreInfo of this container app.
	Apps *map[string]AppStoreInfo `json:"apps,omitempty" yaml:",omitempty"`

	// Architectures The architectures supported by the compose app. If the architecture of the host is not in this list, the compose app will not be installed.
	Architectures *[]string          `json:"architectures,omitempty" yaml:",omitempty"`
	Author        string             `json:"author"`
	Category      string             `json:"category"`
	Description   map[string]string  `json:"description"`
	Developer     string             `json:"developer"`
	Hostname      *string            `json:"hostname,omitempty" yaml:",omitempty"`
	Icon          string             `json:"icon"`
	Image         *map[string]string `json:"image,omitempty"`
	Index         string             `json:"index" yaml:",omitempty"`

	// IsUncontrolled the mean the image tag is custom. not stable or latest
	IsUncontrolled *bool `json:"is_uncontrolled,omitempty" yaml:",omitempty"`

	// Main The main service is one of the services that the user will interact with.
	Main           *string  `json:"main,omitempty" yaml:",omitempty"`
	PortMap        string   `json:"port_map" mapstructure:"port_map" yaml:"port_map,omitempty"`
	Scheme         *Scheme  `json:"scheme,omitempty" yaml:",omitempty"`
	ScreenshotLink []string `json:"screenshot_link" mapstructure:"screenshot_link" yaml:"screenshot_link,omitempty"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID       `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Tagline    map[string]string `json:"tagline"`
	Thumbnail  string            `json:"thumbnail"`
	Tips       TipsStoreInfo     `json:"tips"`
	Title      map[string]string `json:"title"`
}

// ComposeAppStoreInfoLists defines model for ComposeAppStoreInfoLists.
type ComposeAppStoreInfoLists struct {
	Installed *[]StoreAppID                   `json:"installed,omitempty"`
	List      *map[string]ComposeAppStoreInfo `json:"list,omitempty"`
}

// ComposeAppStoreTag defines model for ComposeAppStoreTag.
type ComposeAppStoreTag struct {
	Tag string `json:"tag"`
}

// ComposeAppValidationErrors for list of `ComposeAppValidationErrors`, see **ERRORS** at the bottom of navigation bar.
type ComposeAppValidationErrors struct {
	union json.RawMessage
}

// ComposeAppValidationErrorsPortsInUse This is one of the `ComposeAppValidationErrors` that can be included in the response body of compose app installation.
type ComposeAppValidationErrorsPortsInUse struct {
	PortsInUse *struct {
		TCP *PortList `json:"TCP,omitempty"`
		UDP *PortList `json:"UDP,omitempty"`
	} `json:"ports_in_use,omitempty"`
}

// ComposeAppValidationErrorsPortsOutOfRange This is one of the `ComposeAppValidationErrors` that can be included in the response body of compose app installation.
type ComposeAppValidationErrorsPortsOutOfRange struct {
	PortsOutOfRange *[]string `json:"ports_out_of_range,omitempty"`
}

// ComposeAppWithStoreInfo Schema for `ComposeAppOK` response.
//
// > Do not mistake it as `ComposeAppStoreInfo` which is just store information of a compose app.
type ComposeAppWithStoreInfo struct {
	// Compose See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
	Compose *ComposeApp `json:"compose,omitempty"`

	// IsUncontrolled the mean the image tag is custom. not stable or latest
	IsUncontrolled  *bool                `json:"is_uncontrolled,omitempty" yaml:",omitempty"`
	Status          *string              `json:"status,omitempty"`
	StoreInfo       *ComposeAppStoreInfo `json:"store_info,omitempty"`
	UpdateAvailable *bool                `json:"update_available,omitempty" yaml:",omitempty"`
}

// ContainerSummary See [Go Doc](https://pkg.go.dev/github.com/docker/compose/v2@v2.14.2/pkg/api#ContainerSummary) for the schema structure of `ContainerSummary`.
type ContainerSummary = api.ContainerSummary

// DeviceStoreInfo defines model for DeviceStoreInfo.
type DeviceStoreInfo struct {
	Container   *string            `json:"container,omitempty"`
	Description *map[string]string `json:"description,omitempty"`
}

// EnvStoreInfo defines model for EnvStoreInfo.
type EnvStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// GlobalSetting defines model for GlobalSetting.
type GlobalSetting struct {
	// Description description of the setting
	Description *string `json:"description,omitempty"`

	// Key key of the setting
	Key *string `json:"key,omitempty"`

	// Value value of the setting
	Value string `json:"value"`
}

// Info defines model for Info.
type Info struct {
	// Architecture current architecture
	Architecture *string `json:"architecture,omitempty"`
}

// PortList defines model for PortList.
type PortList = []string

// PortStoreInfo defines model for PortStoreInfo.
type PortStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// Scheme defines model for Scheme.
type Scheme string

// StoreAppAuthorType Type of the author of the app
//
// - `official`: The app is contributed by the app owner, i.e. `author“ and `developer“ are the same.
// - `by_falahos`: The app is contributed by Falah OS team, i.e. `author` is `Falah Core Contributors`
// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_falahos`
type StoreAppAuthorType string

// StoreAppID Store app ID of the compose app (unique across all app stores)
//
// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
type StoreAppID = string

// TipsStoreInfo defines model for TipsStoreInfo.
type TipsStoreInfo struct {
	BeforeInstall map[string]string `json:"before_install" mapstructure:"before_install" yaml:"before_install,omitempty"`
	Custom        *string           `json:"custom,omitempty"`
}

// UpgradableAppInfo Schema for `UpgradableAppListOK` response.
type UpgradableAppInfo struct {
	Icon   string                  `json:"icon"`
	Status UpgradableAppInfoStatus `json:"status"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Title      string      `json:"title"`

	// Version current version of the installed app
	Version string `json:"version"`
}

// UpgradableAppInfoStatus defines model for UpgradableAppInfo.Status.
type UpgradableAppInfoStatus string

// VolumeStoreInfo defines model for VolumeStoreInfo.
type VolumeStoreInfo struct {
	Container   string            `json:"container"`
	Description map[string]string `json:"description"`
}

// WebAppGridItem (internal use ONLY)
type WebAppGridItem struct {
	AppType WebAppGridItemAppType `json:"app_type"`

	// AuthorType Type of the author of the app
	//
	// - `official`: The app is contributed by the app owner, i.e. `author`` and `developer`` are the same.
	// - `by_falahos`: The app is contributed by Falah OS team, i.e. `author` is `Falah Core Contributors`
	// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_falahos`
	AuthorType     *StoreAppAuthorType `json:"author_type,omitempty"`
	Hostname       *string             `json:"hostname,omitempty"`
	Icon           *string             `json:"icon,omitempty"`
	Image          *string             `json:"image,omitempty"`
	Index          *string             `json:"index,omitempty"`
	IsUncontrolled *bool               `json:"is_uncontrolled,omitempty"`
	Name           *string             `json:"name,omitempty"`
	Port           *string             `json:"port,omitempty"`
	Scheme         *Scheme             `json:"scheme,omitempty" yaml:",omitempty"`
	Status         *string             `json:"status,omitempty"`

	// StoreAppId Store app ID of the compose app (unique across all app stores)
	//
	// > The `store_app_id` might be same as app name most of the time. However app name might change, due to cloning for example.
	// > If app name has changed, there is no way to associate it with the original app in the app store, unless we use the `store_app_id`.
	StoreAppID *StoreAppID        `json:"store_app_id,omitempty" mapstructure:"store_app_id" yaml:"store_app_id,omitempty"`
	Title      *map[string]string `json:"title,omitempty"`
}

// WebAppGridItemAppType defines model for WebAppGridItem.AppType.
type WebAppGridItemAppType string

// AppStoreID defines model for AppStoreID.
type AppStoreID = int

// AppStoreURL defines model for AppStoreURL.
type AppStoreURL = string

// CheckPortConflict defines model for CheckPortConflict.
type CheckPortConflict = bool

// ComposeAppID defines model for ComposeAppID.
type ComposeAppID = string

// ContainerID defines model for ContainerID.
type ContainerID = string

// ContainerIDs defines model for ContainerIDs.
type ContainerIDs = string

// DeleteConfigFolder defines model for DeleteConfigFolder.
type DeleteConfigFolder = bool

// DryRun defines model for DryRun.
type DryRun = bool

// Force defines model for Force.
type Force = bool

// GlobalSettingKey defines model for GlobalSettingKey.
type GlobalSettingKey = string

// PullLatestImage defines model for PullLatestImage.
type PullLatestImage = bool

// StoreAppAuthorTypeFilter Type of the author of the app
//
// - `official`: The app is contributed by the app owner, i.e. `author“ and `developer“ are the same.
// - `by_falahos`: The app is contributed by Falah OS team, i.e. `author` is `Falah Core Contributors`
// - `community`: The app is contributed by the community, i.e. any app that is not `official` or `by_falahos`
type StoreAppAuthorTypeFilter = StoreAppAuthorType

// StoreAppCategoryFilter defines model for StoreAppCategoryFilter.
type StoreAppCategoryFilter = string

// StoreAppIDString defines model for StoreAppIDString.
type StoreAppIDString = string

// StoreAppRecommendedFilter defines model for StoreAppRecommendedFilter.
type StoreAppRecommendedFilter = bool

// Uncontrolled defines model for Uncontrolled.
type Uncontrolled = bool

// AppStoreListOK defines model for AppStoreListOK.
type AppStoreListOK struct {
	Data *[]AppStoreMetadata `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// AppStoreRegisterOK defines model for AppStoreRegisterOK.
type AppStoreRegisterOK = BaseResponse

// AppStoreUnregisterOK defines model for AppStoreUnregisterOK.
type AppStoreUnregisterOK = BaseResponse

// CategoryListOK defines model for CategoryListOK.
type CategoryListOK struct {
	Data *[]CategoryInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppBadRequest defines model for ComposeAppBadRequest.
type ComposeAppBadRequest struct {
	// Data for list of `ComposeAppValidationErrors`, see **ERRORS** at the bottom of navigation bar.
	Data *ComposeAppValidationErrors `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppContainersOK defines model for ComposeAppContainersOK.
type ComposeAppContainersOK struct {
	// Data Schema for `ComposeAppContainersOK` response.
	Data *ComposeAppContainers `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppHealthCheckOK defines model for ComposeAppHealthCheckOK.
type ComposeAppHealthCheckOK = BaseResponse

// ComposeAppInstallOK defines model for ComposeAppInstallOK.
type ComposeAppInstallOK = BaseResponse

// ComposeAppListOK defines model for ComposeAppListOK.
type ComposeAppListOK struct {
	Data *map[string]ComposeAppWithStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppLogsOK defines model for ComposeAppLogsOK.
type ComposeAppLogsOK struct {
	Data *string `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppOK defines model for ComposeAppOK.
type ComposeAppOK struct {
	// Data Schema for `ComposeAppOK` response.
	//
	// > Do not mistake it as `ComposeAppStoreInfo` which is just store information of a compose app.
	Data *ComposeAppWithStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreInfoListsOK defines model for ComposeAppStoreInfoListsOK.
type ComposeAppStoreInfoListsOK struct {
	Data *ComposeAppStoreInfoLists `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreInfoOK defines model for ComposeAppStoreInfoOK.
type ComposeAppStoreInfoOK struct {
	Data *ComposeAppStoreInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppStoreTagOK defines model for ComposeAppStoreTagOK.
type ComposeAppStoreTagOK struct {
	Data *ComposeAppStoreTag `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ComposeAppUninstallOK defines model for ComposeAppUninstallOK.
type ComposeAppUninstallOK = BaseResponse

// ComposeAppUpdateOK defines model for ComposeAppUpdateOK.
type ComposeAppUpdateOK = BaseResponse

// ComposeAppUpdateSettingsOK defines model for ComposeAppUpdateSettingsOK.
type ComposeAppUpdateSettingsOK = BaseResponse

// ContainerHealthCheckOK defines model for ContainerHealthCheckOK.
type ContainerHealthCheckOK = BaseResponse

// ContainerRecreateOK defines model for ContainerRecreateOK.
type ContainerRecreateOK = BaseResponse

// GetWebAppGridOK defines model for GetWebAppGridOK.
type GetWebAppGridOK struct {
	Data *[]WebAppGridItem `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GlobalSettingOK defines model for GlobalSettingOK.
type GlobalSettingOK struct {
	Data *GlobalSetting `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// GlobalSettingsOK defines model for GlobalSettingsOK.
type GlobalSettingsOK struct {
	Data *[]GlobalSetting `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// InfoOK defines model for InfoOK.
type InfoOK = Info

// PullImagesOK defines model for PullImagesOK.
type PullImagesOK = BaseResponse

// RequestComposeAppStatusOK defines model for RequestComposeAppStatusOK.
type RequestComposeAppStatusOK = BaseResponse

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseServiceUnavailable defines model for ResponseServiceUnavailable.
type ResponseServiceUnavailable = BaseResponse

// UpgradableAppListOK defines model for UpgradableAppListOK.
type UpgradableAppListOK struct {
	Data *[]UpgradableAppInfo `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// RequestComposeApp See [Compose Specification](https://compose-spec.io) for the schema structure of `ComposeApp`.
type RequestComposeApp = ComposeApp

// RequestComposeAppStatus defines model for RequestComposeAppStatus.
type RequestComposeAppStatus string

// ComposeAppStoreInfoListParams defines parameters for ComposeAppStoreInfoList.
type ComposeAppStoreInfoListParams struct {
	// Category Category of the store app
	Category *StoreAppCategoryFilter `form:"category,omitempty" json:"category,omitempty"`

	// AuthorType Author type of the store app
	AuthorType *StoreAppAuthorTypeFilter `form:"author_type,omitempty" json:"author_type,omitempty"`

	// Recommend The store app is recommended
	Recommend *StoreAppRecommendedFilter `form:"recommend,omitempty" json:"recommend,omitempty"`
}

// RegisterAppStoreParams defines parameters for RegisterAppStore.
type RegisterAppStoreParams struct {
	// Url URL of the app store
	Url *AppStoreURL `form:"url,omitempty" json:"url,omitempty"`
}

// InstallComposeAppParams defines parameters for InstallComposeApp.
type InstallComposeAppParams struct {
	// DryRun Dry run the request without actually excuting it, useful for validation and testing.
	//
	// - `true` - validate only
	// - `false` - validate and execute the request
	DryRun *DryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// CheckPortConflict Check if the port of the app conflicts with ports already in use.
	//
	// - `true` - check port conflict
	// - `false` - skip port conflict check
	CheckPortConflict *CheckPortConflict `form:"check_port_conflict,omitempty" json:"check_port_conflict,omitempty"`

	// Uncontrolled Install the app without any control. the control mean version control, if the app is stable and latest. it is controlled, It will auto update. otherwise it is uncontrolled.
	//
	// - `true` - uncontrolled install
	// - `false` - normal install
	Uncontrolled *Uncontrolled `form:"uncontrolled,omitempty" json:"uncontrolled,omitempty"`
}

// UninstallComposeAppParams defines parameters for UninstallComposeApp.
type UninstallComposeAppParams struct {
	// DeleteConfigFolder Delete the config folder of the app
	DeleteConfigFolder *DeleteConfigFolder `form:"delete_config_folder,omitempty" json:"delete_config_folder,omitempty"`
}

// UpdateComposeAppParams defines parameters for UpdateComposeApp.
type UpdateComposeAppParams struct {
	Force *Force `form:"force,omitempty" json:"force,omitempty"`
}

// ApplyComposeAppSettingsParams defines parameters for ApplyComposeAppSettings.
type ApplyComposeAppSettingsParams struct {
	// DryRun Dry run the request without actually excuting it, useful for validation and testing.
	//
	// - `true` - validate only
	// - `false` - validate and execute the request
	DryRun *DryRun `form:"dry_run,omitempty" json:"dry_run,omitempty"`

	// CheckPortConflict Check if the port of the app conflicts with ports already in use.
	//
	// - `true` - check port conflict
	// - `false` - skip port conflict check
	CheckPortConflict *CheckPortConflict `form:"check_port_conflict,omitempty" json:"check_port_conflict,omitempty"`

	// Uncontrolled Install the app without any control. the control mean version control, if the app is stable and latest. it is controlled, It will auto update. otherwise it is uncontrolled.
	//
	// - `true` - uncontrolled install
	// - `false` - normal install
	Uncontrolled *Uncontrolled `form:"uncontrolled,omitempty" json:"uncontrolled,omitempty"`
}

// ComposeAppLogsParams defines parameters for ComposeAppLogs.
type ComposeAppLogsParams struct {
	// Lines Number of lines to show from the end of the logs for each compose app.
	//
	// - show all logs if `-1`
	Lines *int `form:"lines,omitempty" json:"lines,omitempty"`
}

// SetComposeAppStatusJSONBody defines parameters for SetComposeAppStatus.
type SetComposeAppStatusJSONBody string

// RecreateContainerByIDParams defines parameters for RecreateContainerByID.
type RecreateContainerByIDParams struct {
	// Pull Try to pull the latest image from the registry
	Pull  *PullLatestImage `form:"pull,omitempty" json:"pull,omitempty"`
	Force *Force           `form:"force,omitempty" json:"force,omitempty"`
}

// ConvertJSONBody defines parameters for Convert.
type ConvertJSONBody = map[string]interface{}

// ConvertParams defines parameters for Convert.
type ConvertParams struct {
	Type *ConvertParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// ConvertParamsType defines parameters for Convert.
type ConvertParamsType string

// PullImagesParams defines parameters for PullImages.
type PullImagesParams struct {
	// ContainerIds a list of comma separated container IDs
	ContainerIds *ContainerIDs `form:"container_ids,omitempty" json:"container_ids,omitempty"`
}

// RegisterAppStoreSyncParams defines parameters for RegisterAppStoreSync.
type RegisterAppStoreSyncParams struct {
	// Url URL of the app store
	Url *AppStoreURL `form:"url,omitempty" json:"url,omitempty"`
}

// InstallComposeAppJSONRequestBody defines body for InstallComposeApp for application/json ContentType.
type InstallComposeAppJSONRequestBody = ComposeApp

// ApplyComposeAppSettingsJSONRequestBody defines body for ApplyComposeAppSettings for application/json ContentType.
type ApplyComposeAppSettingsJSONRequestBody = ComposeApp

// SetComposeAppStatusJSONRequestBody defines body for SetComposeAppStatus for application/json ContentType.
type SetComposeAppStatusJSONRequestBody SetComposeAppStatusJSONBody

// ConvertJSONRequestBody defines body for Convert for application/json ContentType.
type ConvertJSONRequestBody = ConvertJSONBody

// UpdateGlobalSettingJSONRequestBody defines body for UpdateGlobalSetting for application/json ContentType.
type UpdateGlobalSettingJSONRequestBody = GlobalSetting

// AsComposeAppValidationErrorsPortsInUse returns the union data inside the ComposeAppValidationErrors as a ComposeAppValidationErrorsPortsInUse
func (t ComposeAppValidationErrors) AsComposeAppValidationErrorsPortsInUse() (ComposeAppValidationErrorsPortsInUse, error) {
	var body ComposeAppValidationErrorsPortsInUse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeAppValidationErrorsPortsInUse overwrites any union data inside the ComposeAppValidationErrors as the provided ComposeAppValidationErrorsPortsInUse
func (t *ComposeAppValidationErrors) FromComposeAppValidationErrorsPortsInUse(v ComposeAppValidationErrorsPortsInUse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeAppValidationErrorsPortsInUse performs a merge with any union data inside the ComposeAppValidationErrors, using the provided ComposeAppValidationErrorsPortsInUse
func (t *ComposeAppValidationErrors) MergeComposeAppValidationErrorsPortsInUse(v ComposeAppValidationErrorsPortsInUse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

// AsComposeAppValidationErrorsPortsOutOfRange returns the union data inside the ComposeAppValidationErrors as a ComposeAppValidationErrorsPortsOutOfRange
func (t ComposeAppValidationErrors) AsComposeAppValidationErrorsPortsOutOfRange() (ComposeAppValidationErrorsPortsOutOfRange, error) {
	var body ComposeAppValidationErrorsPortsOutOfRange
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComposeAppValidationErrorsPortsOutOfRange overwrites any union data inside the ComposeAppValidationErrors as the provided ComposeAppValidationErrorsPortsOutOfRange
func (t *ComposeAppValidationErrors) FromComposeAppValidationErrorsPortsOutOfRange(v ComposeAppValidationErrorsPortsOutOfRange) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComposeAppValidationErrorsPortsOutOfRange performs a merge with any union data inside the ComposeAppValidationErrors, using the provided ComposeAppValidationErrorsPortsOutOfRange
func (t *ComposeAppValidationErrors) MergeComposeAppValidationErrorsPortsOutOfRange(v ComposeAppValidationErrorsPortsOutOfRange) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JsonMerge(b, t.union)
	t.union = merged
	return err
}

func (t ComposeAppValidationErrors) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ComposeAppValidationErrors) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get app list from registered app stores
	// (GET /apps)
	ComposeAppStoreInfoList(ctx echo.Context, params ComposeAppStoreInfoListParams) error
	// Get the list of upgradable apps from installed app.
	// (GET /apps/upgradable)
	UpgradableAppList(ctx echo.Context) error
	// Get app info from registered app stores
	// (GET /apps/{id})
	ComposeAppStoreInfo(ctx echo.Context, id StoreAppIDString) error
	// Get compose details of an app from registered app stores
	// (GET /apps/{id}/compose)
	ComposeApp(ctx echo.Context, id StoreAppIDString) error
	// Get app stable version from registered app stores
	// (GET /apps/{id}/stable)
	ComposeAppMainStableTag(ctx echo.Context, id StoreAppIDString) error
	// Get server of app stable version from registered app stores
	// (GET /apps/{id}/stable/{serviceName})
	ComposeAppServiceStableTag(ctx echo.Context, id StoreAppIDString, serviceName string) error
	// Get the list of registered app stores
	// (GET /appstore)
	AppStoreList(ctx echo.Context) error
	// Register an app store
	// (POST /appstore)
	RegisterAppStore(ctx echo.Context, params RegisterAppStoreParams) error
	// Unregister an app store
	// (DELETE /appstore/{id})
	UnregisterAppStore(ctx echo.Context, id AppStoreID) error
	// Get the list of app categories
	// (GET /categories)
	CategoryList(ctx echo.Context) error
	// Get the list of installed compose apps
	// (GET /compose)
	MyComposeAppList(ctx echo.Context) error
	// Install a compose app
	// (POST /compose)
	InstallComposeApp(ctx echo.Context, params InstallComposeAppParams) error
	// Uninstall a compose app
	// (DELETE /compose/{id})
	UninstallComposeApp(ctx echo.Context, id ComposeAppID, params UninstallComposeAppParams) error
	// Get compose details of a locally installed app
	// (GET /compose/{id})
	MyComposeApp(ctx echo.Context, id ComposeAppID) error
	// Update container images of compose app to match the compose app in AppStore.
	// (PATCH /compose/{id})
	UpdateComposeApp(ctx echo.Context, id ComposeAppID, params UpdateComposeAppParams) error
	// Apply settings to a compose app
	// (PUT /compose/{id})
	ApplyComposeAppSettings(ctx echo.Context, id ComposeAppID, params ApplyComposeAppSettingsParams) error
	// Get the list of containers of a compose app
	// (GET /compose/{id}/containers)
	ComposeAppContainers(ctx echo.Context, id ComposeAppID) error
	// Check if the compose app is running healthy
	// (GET /compose/{id}/healthcheck)
	CheckComposeAppHealthByID(ctx echo.Context, id ComposeAppID) error
	// Get the logs of a compose app
	// (GET /compose/{id}/logs)
	ComposeAppLogs(ctx echo.Context, id ComposeAppID, params ComposeAppLogsParams) error
	// Start/restart/stop a compose app
	// (PUT /compose/{id}/status)
	SetComposeAppStatus(ctx echo.Context, id ComposeAppID) error
	// Recreate the container app
	// (PATCH /container/{id})
	RecreateContainerByID(ctx echo.Context, id ContainerID, params RecreateContainerByIDParams) error
	// Check if the container app is running healthy
	// (GET /container/{id}/healthcheck)
	CheckContainerHealthByID(ctx echo.Context, id ContainerID) error
	// Convert to compose app from another file format
	// (POST /convert)
	Convert(ctx echo.Context, params ConvertParams) error
	// Get all global settings
	// (GET /global)
	GetGlobalSettings(ctx echo.Context) error
	// Delete a global setting
	// (DELETE /global/{key})
	DeleteGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Get a global setting
	// (GET /global/{key})
	GetGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Update a global setting
	// (PUT /global/{key})
	UpdateGlobalSetting(ctx echo.Context, key GlobalSettingKey) error
	// Post a batch pull request specified images
	// (POST /image)
	PullImages(ctx echo.Context, params PullImagesParams) error
	// Get certain common information
	// (GET /info)
	Info(ctx echo.Context) error
	// (internal use ONLY)
	// (GET /web/appgrid)
	GetAppGrid(ctx echo.Context) error
	// Register an app store in Sync.
	// (POST /web/sync/appstore)
	RegisterAppStoreSync(ctx echo.Context, params RegisterAppStoreSyncParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ComposeAppStoreInfoList converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppStoreInfoList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ComposeAppStoreInfoListParams
	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameter("form", true, false, "category", ctx.QueryParams(), &params.Category)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter category: %s", err))
	}

	// ------------- Optional query parameter "author_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "author_type", ctx.QueryParams(), &params.AuthorType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter author_type: %s", err))
	}

	// ------------- Optional query parameter "recommend" -------------

	err = runtime.BindQueryParameter("form", true, false, "recommend", ctx.QueryParams(), &params.Recommend)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter recommend: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppStoreInfoList(ctx, params)
	return err
}

// UpgradableAppList converts echo context to params.
func (w *ServerInterfaceWrapper) UpgradableAppList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpgradableAppList(ctx)
	return err
}

// ComposeAppStoreInfo converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppStoreInfo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppStoreInfo(ctx, id)
	return err
}

// ComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeApp(ctx, id)
	return err
}

// ComposeAppMainStableTag converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppMainStableTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppMainStableTag(ctx, id)
	return err
}

// ComposeAppServiceStableTag converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppServiceStableTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id StoreAppIDString

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "serviceName" -------------
	var serviceName string

	err = runtime.BindStyledParameterWithLocation("simple", false, "serviceName", runtime.ParamLocationPath, ctx.Param("serviceName"), &serviceName)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceName: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppServiceStableTag(ctx, id, serviceName)
	return err
}

// AppStoreList converts echo context to params.
func (w *ServerInterfaceWrapper) AppStoreList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AppStoreList(ctx)
	return err
}

// RegisterAppStore converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAppStore(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterAppStoreParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterAppStore(ctx, params)
	return err
}

// UnregisterAppStore converts echo context to params.
func (w *ServerInterfaceWrapper) UnregisterAppStore(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id AppStoreID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UnregisterAppStore(ctx, id)
	return err
}

// CategoryList converts echo context to params.
func (w *ServerInterfaceWrapper) CategoryList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CategoryList(ctx)
	return err
}

// MyComposeAppList converts echo context to params.
func (w *ServerInterfaceWrapper) MyComposeAppList(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MyComposeAppList(ctx)
	return err
}

// InstallComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) InstallComposeApp(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params InstallComposeAppParams
	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", ctx.QueryParams(), &params.DryRun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dry_run: %s", err))
	}

	// ------------- Optional query parameter "check_port_conflict" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_port_conflict", ctx.QueryParams(), &params.CheckPortConflict)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter check_port_conflict: %s", err))
	}

	// ------------- Optional query parameter "uncontrolled" -------------

	err = runtime.BindQueryParameter("form", true, false, "uncontrolled", ctx.QueryParams(), &params.Uncontrolled)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uncontrolled: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InstallComposeApp(ctx, params)
	return err
}

// UninstallComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) UninstallComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UninstallComposeAppParams
	// ------------- Optional query parameter "delete_config_folder" -------------

	err = runtime.BindQueryParameter("form", true, false, "delete_config_folder", ctx.QueryParams(), &params.DeleteConfigFolder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter delete_config_folder: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UninstallComposeApp(ctx, id, params)
	return err
}

// MyComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) MyComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.MyComposeApp(ctx, id)
	return err
}

// UpdateComposeApp converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateComposeApp(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateComposeAppParams
	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", ctx.QueryParams(), &params.Force)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter force: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateComposeApp(ctx, id, params)
	return err
}

// ApplyComposeAppSettings converts echo context to params.
func (w *ServerInterfaceWrapper) ApplyComposeAppSettings(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyComposeAppSettingsParams
	// ------------- Optional query parameter "dry_run" -------------

	err = runtime.BindQueryParameter("form", true, false, "dry_run", ctx.QueryParams(), &params.DryRun)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter dry_run: %s", err))
	}

	// ------------- Optional query parameter "check_port_conflict" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_port_conflict", ctx.QueryParams(), &params.CheckPortConflict)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter check_port_conflict: %s", err))
	}

	// ------------- Optional query parameter "uncontrolled" -------------

	err = runtime.BindQueryParameter("form", true, false, "uncontrolled", ctx.QueryParams(), &params.Uncontrolled)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter uncontrolled: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ApplyComposeAppSettings(ctx, id, params)
	return err
}

// ComposeAppContainers converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppContainers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppContainers(ctx, id)
	return err
}

// CheckComposeAppHealthByID converts echo context to params.
func (w *ServerInterfaceWrapper) CheckComposeAppHealthByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckComposeAppHealthByID(ctx, id)
	return err
}

// ComposeAppLogs converts echo context to params.
func (w *ServerInterfaceWrapper) ComposeAppLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ComposeAppLogsParams
	// ------------- Optional query parameter "lines" -------------

	err = runtime.BindQueryParameter("form", true, false, "lines", ctx.QueryParams(), &params.Lines)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter lines: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ComposeAppLogs(ctx, id, params)
	return err
}

// SetComposeAppStatus converts echo context to params.
func (w *ServerInterfaceWrapper) SetComposeAppStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ComposeAppID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SetComposeAppStatus(ctx, id)
	return err
}

// RecreateContainerByID converts echo context to params.
func (w *ServerInterfaceWrapper) RecreateContainerByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ContainerID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RecreateContainerByIDParams
	// ------------- Optional query parameter "pull" -------------

	err = runtime.BindQueryParameter("form", true, false, "pull", ctx.QueryParams(), &params.Pull)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter pull: %s", err))
	}

	// ------------- Optional query parameter "force" -------------

	err = runtime.BindQueryParameter("form", true, false, "force", ctx.QueryParams(), &params.Force)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter force: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RecreateContainerByID(ctx, id, params)
	return err
}

// CheckContainerHealthByID converts echo context to params.
func (w *ServerInterfaceWrapper) CheckContainerHealthByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ContainerID

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CheckContainerHealthByID(ctx, id)
	return err
}

// Convert converts echo context to params.
func (w *ServerInterfaceWrapper) Convert(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ConvertParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Convert(ctx, params)
	return err
}

// GetGlobalSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetGlobalSettings(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGlobalSettings(ctx)
	return err
}

// DeleteGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteGlobalSetting(ctx, key)
	return err
}

// GetGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) GetGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetGlobalSetting(ctx, key)
	return err
}

// UpdateGlobalSetting converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGlobalSetting(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key GlobalSettingKey

	err = runtime.BindStyledParameterWithLocation("simple", false, "key", runtime.ParamLocationPath, ctx.Param("key"), &key)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateGlobalSetting(ctx, key)
	return err
}

// PullImages converts echo context to params.
func (w *ServerInterfaceWrapper) PullImages(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params PullImagesParams
	// ------------- Optional query parameter "container_ids" -------------

	err = runtime.BindQueryParameter("form", true, false, "container_ids", ctx.QueryParams(), &params.ContainerIds)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter container_ids: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PullImages(ctx, params)
	return err
}

// Info converts echo context to params.
func (w *ServerInterfaceWrapper) Info(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Info(ctx)
	return err
}

// GetAppGrid converts echo context to params.
func (w *ServerInterfaceWrapper) GetAppGrid(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAppGrid(ctx)
	return err
}

// RegisterAppStoreSync converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterAppStoreSync(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params RegisterAppStoreSyncParams
	// ------------- Optional query parameter "url" -------------

	err = runtime.BindQueryParameter("form", true, false, "url", ctx.QueryParams(), &params.Url)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter url: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterAppStoreSync(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/apps", wrapper.ComposeAppStoreInfoList)
	router.GET(baseURL+"/apps/upgradable", wrapper.UpgradableAppList)
	router.GET(baseURL+"/apps/:id", wrapper.ComposeAppStoreInfo)
	router.GET(baseURL+"/apps/:id/compose", wrapper.ComposeApp)
	router.GET(baseURL+"/apps/:id/stable", wrapper.ComposeAppMainStableTag)
	router.GET(baseURL+"/apps/:id/stable/:serviceName", wrapper.ComposeAppServiceStableTag)
	router.GET(baseURL+"/appstore", wrapper.AppStoreList)
	router.POST(baseURL+"/appstore", wrapper.RegisterAppStore)
	router.DELETE(baseURL+"/appstore/:id", wrapper.UnregisterAppStore)
	router.GET(baseURL+"/categories", wrapper.CategoryList)
	router.GET(baseURL+"/compose", wrapper.MyComposeAppList)
	router.POST(baseURL+"/compose", wrapper.InstallComposeApp)
	router.DELETE(baseURL+"/compose/:id", wrapper.UninstallComposeApp)
	router.GET(baseURL+"/compose/:id", wrapper.MyComposeApp)
	router.PATCH(baseURL+"/compose/:id", wrapper.UpdateComposeApp)
	router.PUT(baseURL+"/compose/:id", wrapper.ApplyComposeAppSettings)
	router.GET(baseURL+"/compose/:id/containers", wrapper.ComposeAppContainers)
	router.GET(baseURL+"/compose/:id/healthcheck", wrapper.CheckComposeAppHealthByID)
	router.GET(baseURL+"/compose/:id/logs", wrapper.ComposeAppLogs)
	router.PUT(baseURL+"/compose/:id/status", wrapper.SetComposeAppStatus)
	router.PATCH(baseURL+"/container/:id", wrapper.RecreateContainerByID)
	router.GET(baseURL+"/container/:id/healthcheck", wrapper.CheckContainerHealthByID)
	router.POST(baseURL+"/convert", wrapper.Convert)
	router.GET(baseURL+"/global", wrapper.GetGlobalSettings)
	router.DELETE(baseURL+"/global/:key", wrapper.DeleteGlobalSetting)
	router.GET(baseURL+"/global/:key", wrapper.GetGlobalSetting)
	router.PUT(baseURL+"/global/:key", wrapper.UpdateGlobalSetting)
	router.POST(baseURL+"/image", wrapper.PullImages)
	router.GET(baseURL+"/info", wrapper.Info)
	router.GET(baseURL+"/web/appgrid", wrapper.GetAppGrid)
	router.POST(baseURL+"/web/sync/appstore", wrapper.RegisterAppStoreSync)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9aXPcNhLoX0Fxt+rFKc6MbCt2rKpUrWzFjl6cSKVj87KWSoMhe2YQkQADgCPPuvTf",
	"X+EiCR5zy1L2+LCxhjgajUajL3R/CSKWZowClSI4+BJkmOMUJHD912GWnUvG4fhI/RWDiDjJJGE0OAiO",
	"jxAbIzkFhLMMCdUsCAOiPmVYToMwoDiF4CAgcRAGHP7MCYc4OJA8hzAQ0RRSrEaFzzjNEggO9sJAzjPd",
	"g0qYAA/u78MChMuzj00YLs8+dgLxZw58XkKR8yRonTaYSpmJg8FgQuQ0H/Ujlg6OI/htihO4gGg6eI8T",
	"PEUn5z0HSlAAKiQndKLhfDeF6PaUcfmO0XFCItmEVjdBxMCbMS6rsEe2m0B3RE71Z4FwwgHHc0QoygX0",
	"r+gV7aGhwuAQ9VCkx9MDud76+xgnQjcQtyTzv5s+V7QDSfrrjepx43p4SIthjPNEuk20WBgxlgCmBg2K",
	"mgQcZlkbzRxmGTJ0g1FkWurFf6OoY4YToBJJVnzKOPsDIokUdM+2I65AzGkkp2q3WnePUYkJBd4GdfFR",
	"wU6o3rIjFt0CRzynkqSKIsqZ9t7A673xPn4dxy/H0f7LGF7h56Nofy/e/y56/Wb8/Xevv9vfh+cvX71+",
	"A9+NnuP91/t7b/Ze7uPXEbx68XyjhS5ckmiuCaOECE2AEUtTjASoky8hVqRSrFZ00Ylrc0Ni0XGsYP/l",
	"93vfv37Vi19/96a3P3rxqofHz8e9N6++x/uv9l7FL9+8ad2LI0hAgjpGZPKeJTHwJvimjd6JSDdEY92y",
	"cqI6QI91zxvT68b0WpPGj/j8LKctQPG5IggNgNopEFIfZpZLhCOZ4ySZI/gc5ZLQCSIyVId6nCdozDia",
	"4YTEWI2EMI2RBKFa1Y+8bQWI0WTuH/bik+oOnyHKLYIsKJ2HPubzG57TdiTo4Vux8J7xCFTbtjHH+uOa",
	"I35I2Agn5yDVyn+GeRPDP8Pc7fBEN0bCtG4/M7cwX5E7nJz++Ovh8c3h6fHNzz/+3kqWp3mSfMRqX45T",
	"PIEmcBd8rphXlieJhjDRjRFRrdGYs9TuxoQIqXHVhjjVe1286UvpMMsOczll/GKewXuSyLZjY1ogNYbD",
	"o74zF5wXrLvc6GmrcP2dwzg4CP42KOWHgfkqBk2APDjfYQkTxuddULrvq4IY2fYdjCiaYtm6ow6e46Nz",
	"82MDknM3c/utlVPyZw4IR5wJdVknpRQiHva+cqCfgWLfQGOIu7B5UcUgIgLxsk8HQosW61LiJVU3A2dJ",
	"ohbXkBipkNgeDgVLwRvpHNl+fcfS1R8oBUzRDLhQXNH+GDoByq5GSDxKDNMzB66PiFQfSkhCdKwYsdqe",
	"XDKUZ4pN9hGTU+B3RIDtkFeAr/Pd6jdEzDp89ksZT3FSfusSQ6sYat35LuzeG7oBId+ymIC+08/MD6XQ",
	"pX5UEwDV8ifOsoRE+lYZ/CGYvrNWO8KVIdXM1YHmOE18Wv0bio045E7H74e/fEQWjisqgM9IBOLgiiLU",
	"7/ev6MqcxAPjPmwIZuVhrE7ZOGL3YRNV5xLLXKyFMKB5Ghx8CoTE3Ezi/iUky4Lr5kldCLIwEDSA1Tst",
	"MkYFeFrYRyLkyc9rQYyT5GQcHHxajOW3WMCZnTG4D78EGWcZcGmpLMZSD0YkpGLZjjlgfwGJdcf7AiuY",
	"czxXSLluQczJz0FF2zvTtyTwr7Dc5cBcUv4UwHHX4l+CDBywx3TM1iOB8oS+xbE9tY+32NWY0z8L4f1H",
	"zhkXXSt8i2MnjvtLLZQ18Zg7u9piS1hX3cifACdyqs0fKy2vuFm+BCkIoaXtIGOKo656cfgrXg6ilU3W",
	"xP4uIXjsY43jmKh5cHLqfV+NKH4jcmpMhf6BZ6M/IJKrEspHNnnUA1CKNFf53t7LKGEToQQW9Ueb2W+l",
	"RT39E13bPL2sdpmv2+C0FA3FBIrQ/wJszod31c0uev2FFrjW2i7w5C+ytAu88hG9pOTR+f+lVksfHQBr",
	"fhOPAIgVK56wtGAhPIOIw2Ns1geQv8HoMMs+cBI/eR2gBPVYQrqeFuDZgp8qw/GAXGM94slvXW1l6+zc",
	"BpffIkjcBdU+2WmeJNoc//X5VYdB6VFNBK7NWppzK/9UmupZqanuBnG1QV3Tqsd8E1iL/jsDtDqia3dM",
	"JXCqDgWfAdd6/qYAu6GQGQuZwXYGfefwrtOvTL5nOY03hf9XJpEZYGcwe0O6hptf/+Y47Pa4mxbnxph9",
	"SfEMkwSPzMybwGhHQtWhdgZ0x+CX2YTjWP31BCwOK91EHsTrWhMLdPrRTGqUhnfKKPnoiCHKJEqJkPhW",
	"u4awQN8SOmY8Ne55NkZupG/R3ZREUxQzELobfCZC9oOwvmLQDpCVF32k27fZU8ySw+Bzj+GM9CIWwwRo",
	"Dz5LjnsST/TQRlsPQpaq2TI515gAOlsdgh/pbMfTE+c1b/FxHhjXXdPCEgY6EGplsE8ZlzuGe8aSPF1j",
	"7/6p2+8UiPuqi+iTxaTdUIehEtCwILfrMJBEalQX8Gg3NtXe9IqLo/DWHNQPK9G3REooSfNUB+lxwPEJ",
	"Tea1CBkXtKfWN2E96+88PtI8Tc1xwxmTPgE0Qut6KSY06JyjJIucJ1tG8Q0wj6ZkBgMOYzGYAo7FQM3e",
	"/zfJlkLgL/Ly7KPZJY/xNVBZsP4667EfEAeZcwoxGs2RMHe3IDFYjzcHRATCdO5FmwWtTkfP/dIAJGI5",
	"9XfiZbjOFtd5rbelxHrjj7DE6C2ObvNM8Uuxyq6OWQ2uYKQH6HFwsZ1LxzAEW4zwPNyWeM0fVaDMqpYD",
	"4wdEtoSXAKBPziN8nkFExvbqvf7G0bN1qfdEBlGfsGc6WExHxWh+g4TkeSRzrgN6huVsw35QN8Lbxdkf",
	"1X9E/9SEWFa/9UiqWIoC1+JBN1WcBstpcBBUjlgVuuKPCRuYHvcdPq4WTJjFqLUN271iQ+R84s3rNfJG",
	"3syRYUc4z9MU87na94rQtnVI58GX+6ZPJAw0t1s57Kfd0Nw83lidtg0R4duFw5ZYoluYKz6kSFCRhwuL",
	"ckGjOMtCE8E4BTTDSQ6utXcFyakN0Sl6mbCQCtJLVBjsNQ6bvdpMcBOxA3tjCkRolOSxDtqxoUVF/EXr",
	"+VhbPNC3iAR9BEV79JXXBIk8U8fLcPkaSH10bIObKl1cGNyUCR2npORMvRoidBBvWB/FxDqpZiNwAUk6",
	"pKmK308BTuNX+4FaQfpqX8kKhXjT4KkO1auvJNiF6GViD9tEhndqy9Wh5WSUS8ZFm+hYxAW2M+9G+9qd",
	"1nV8Gv0qNAv0JheKnzna1Ve2JkpCc5YLNFb3oyLtKWeU/NuoFBlnE47TPjqWlW9gWgs0AnkHQJG8Y4hx",
	"lKrFK1znErgiccQBJ0iSFEIk8BiSuRpR7RPEJvI043MFDMxB9NHvLOdISXsKuHnxB04YNVf3nOUoBi2B",
	"6HD8KVO7emdEEGmi7hiHOFS/KcnE/TrFHGLzgEGwFBSN8hhlmMu5YQpTdoeI/D8CSY6pSIlUEDIl6Cj6",
	"IdpwAbIftDHLGGaQqI3w9/O8m2OGgTozzfs7aBPn1ldoorrsU9zZMe3/IWJIyIz3KcjBZLpEGP2HugkU",
	"8xWDYj0DNUE/a19YoU1tQ6UN/asN7YTG8Nlf52BHCBQ3+cKAUUUTOgZUE4eOo5ZYH6koF5Klfc3kbAQo",
	"4zYA1OdzLpzScjB7Fyku6cV7Bo2Iy42W5C705iWgviAbCalWoM6ai2+28ZFITrHUv+QCuOHi+kjgyDwk",
	"qLFwX1iwC3R3smzMSdHQzTTczQbqh0Ipznzq+P7l9/vrjp/irBBktffODhy6md0vNQi02AJL49FNK92e",
	"A1AxZfImIfTWA/zTbs7vSQb0PAOIL0DIQTlh77k9yw87yws9y+LbfI2LubYxdfwV+1P7UN8mrf/jLLsx",
	"2tkqjweM8iXxJCF0a073noO6GyHKOZibKCbCCA/qivTuZGHuZMlY0n4RyWmejigmyQNw//8LSTIfEzoo",
	"Jun/kbXeAJJkS6X5C5IJ3xJluMSOhJu2OC/fVGUluLD6RqPKG6u3ur1RwxYic1RQxb1bjMWEu6gqXOl6",
	"QfxRi6HLCcorW/pqlOrZpMNAiebbx9Utjqlri85prkyaH0tKnT3f679ofVdS3TvVzUdhI8xVLY/OV/AI",
	"dI9xyrgUx/TSegq2GOQklyfjM0wnENxf1zXXsRIP7IvHYfdAQ8UkAH377Y9nZydn599+i+yNPGJSslT1",
	"pnhGJoZFjDDvd1uBSoax0upbpAYiapLCIsiN9BBharQ+X+11thM0YvHcvvos1EVL+XqwpnFFm5dviDr7",
	"LTbNi3enq9jk1ZnT/qejNZo3dP5WK8CayK5QydPGOMvlDRvfcAdqwZKWSFrdOHLusrWQ6MeGrmi488x1",
	"V/SKLnKuDVu43dA61ohAf+RCotLGU/HCea/x2qyC+uM6T4y+rk7SZdB6YB1FFA+fSkriOaVGTF9qXzey",
	"HLHUsMEtZt7f3Xj+8wISM2kHEFss23sR74y87Qb5Dwwdsai0wGe3k/6E9WOYVZ1L5sWbs3kPZi/+MXvR",
	"f77ff6HaD3BG/lafbqnp3m++1ICPM9JvLGmhHR9npNWK31iLW4N9j+87o1vcSRaImpVAYSzm5IFNbR9O",
	"L5FxeHaISJ4re1XgL/71wGBfkBTQvxiF5UJ0CaIPwXU9rrC5uhrAPrVX/ipNEe45feVtfAb08Bgdnh6j",
	"n/WD+sbybtve6t+Wb/VbR62/uF/KeLQzoTmP8TEsmEnc9j6b/y0VeU3CADPRtY1lbPGvVKzgTXiinHOg",
	"0jPhe/A4u/sKzsNCFtrl/W+GXftIqMke9kj8BiN0ebzdeTgvDELFc3WtmOtwCfN61/6p2Xvzze5GV2pL",
	"woOmcFlJumDU4kqyEvvcnI3HJCI4GR6gi/KJe+T8HKWnRX1hdxR4iEgf+mhoRhwOtW1jWCjV6gdu0oAI",
	"nCpZrIeGo/nNGCd4ysTCeZyZAknAaW0e1XzY4YoZ6kkilqY5JXK+dC1FSzsHpnPdWkvX1t9VYkbJVNUV",
	"GMnKbq1rFYRB2SQIg2KKIAxyekvZHVU73yWAlWkfcJkwo9WkqSbuzTBXF6xQEJQUcFLCUv74du6w6v38",
	"rgJf+eulg9TLVbE8S0XdHbg4T0VFPFf7NKza6oYoJZOp9iMq8lHSuuqpbcwpE0UCK0lS6KOf2B3MjOPV",
	"NtGdo6lSYUIU58ablDAlamphyDKBfgHB8bjsPcXC9o3DMv6FMnSHdaIVLASLCJZaj9A+JwUK42RCKE6s",
	"nuXnBgtRThMQAt1pG7vR8LwFLzKxLyeX46NgcaRQZRvXNLxWLail1bXya40l+aa/Bo8fwdiI8VoR3V6Y",
	"yYTe0FwAF8gM7rRchdL7NX3ttdXXoC3W7/9ew4DRx2q5YPRvSCp4R3MN7lKhoDb5dT2Mdrli3BJ1uyic",
	"5VEdixXt0DJVEmsrq1bbiPEtdCiFGxn4nUW6XO0XoDeX5wdXpaH5Krhvg9WmhumWwVzuGMumChOvjVBY",
	"2yJqDc5u3rB+LIuMHnoLK+GXJQVYvmRU4Xqs6MqqlUlf9tWCGGyOtZhwiCQz4VGby2i1d2GN3fuGuAcM",
	"ikef/Prx92eNM6JQLq2c5Qh19sJs6+y5+W8VBu1IaKPcan6rDdJarRxi8GQCBsrZJ0QCHuj/P3je2qfp",
	"+ndOlmbbpuFsWUqjMrSyNerbD1Dd29tr4zvr+n8X2r4egq11HcAV/WoNr22Xo82dB/10Xzs6iZybhZsD",
	"E0UgxI1kt0CLrH1TwCb9oRVPDGXbqKRKCFdGlOavVVLS/Xgiyoi+sI0sd0URQsh8ECznEaAUYoJ/uAq+",
	"yTiMgYtexBLGe2YTD1CM+e2zqwAJHgmQP1wVx4Pju74xV6kL2z5WaYZ4J2zCdAj3wEr+7r83I0wp8Bs1",
	"wQ1VQunN93t72Wd1Vq6CTcFN1EAPCq+8I3qSm1GSw2KQSTpBOFFAOFZhAHsMqAxEgxo1XNFCoTzMMvQL",
	"pngCqbqlU/1Po1okZAzRPEogtB4VHUNn7m1CJ0qAr/6l82/Zf7EsM/8yNqAQgYy08+E944gIkaspjOc/",
	"yoW6wEWIsgSwADQjghhH36cPRP6UjxCHjAmiLrvSErzsbcEzpZz+wQhFn1jO0REREeNx2T82P/Qnk8Et",
	"/fNwNHo7gv/3zKgcTlLoQtLh6XFF8jgIZi8UU2AZUJyR4CB42d/rv7TWXX3gBy4MeAItuYg/gNT+UKFk",
	"I/9xSJJUtUdhAgjdvWOAVYxM84jjuMxpVvexa2DKbNIdHuKyyaAjP2SXW7ilZyMD5hp9m6kU769ridhe",
	"7O113QJFu8GCjCf3YfDdKkMsenKq2bvzX+htNMdGSLNRLlWZEXKtkm9CKIyBwsKFUpBTFgtzYWhiGeSF",
	"lNpJN99cnBydPGshgoaOE2yCvLb3iQ+DNZ2h1QYE5J50bineUxb6K2LwC4nvF54576gJ++TD82NW7DGH",
	"nhnHirPWPV2EAbtw96ECYNhHJxXntf7Jxd8PFVMfVoLvi6FDE9uLhcmJKbTNMIZMHQYazd3Qqx39jY99",
	"kYZ1Z+fOEM/+3v7qxFM8jX64s6pfKmx9VhWlDSou7laKO4wiyCQaMTnVm+i97LW24nqap6HLomnSBDuf",
	"5dCMNURGZnSmtZ8uLk5dSjtNuvYBQ6O5UPcykqxlwtAPmNBxryPwrXlD46Ps2RX35x6gUyzRmCUJuxNr",
	"P6haTNaPT81Pj4gd54hBYpKI8kXpjqjaBE8sZKM2vsKKQ984W7thr+gCT54pqLz4525+u2D7f8GEnuu5",
	"LvDkiXA2k4HrCTI2f1N2SgyDL3Ybf8Up3D8J0rAZFnZJHeGXjiwO1aB+/5FVS4rxCqbWKhnxH0ub9ik1",
	"Gz8ElepnyWtLy9WUzhsJyrWc0A8vI2+AojDImFgHKy7rc6XQznpHqlosaDN6bklAral5DdxWki/prm9W",
	"71rNO7Tj/XQLcle1e0+/IokXmo2pn7KOYlhkz956W4+PttxVL5P3E+JSJVxrbo99VmFtyuvxoGo+8Y14",
	"UC0h+WL+oTXYEtrlK1ui2qhVoR7CcYwqH1qW+cvcz7EcbHfNfTWGW9ofqta4CuKcnrOc4brCG375kqIk",
	"ja1l9a6leAPKOJsRL6y9VPWslaKn40ZcwaMpFkrLGwEa2jF0MOoBauqZLkuAjpC3/YwWt4kSV0Dz2xQo",
	"GtqqRj+YCh5ENFaiC3MgI/2EiEhdUqmoomRMJlVUtEmDFrFbqIu2ltQKdspmgbkVOnkFWQzvdCVE5t3E",
	"W6kyMmiWGLnf7gCVmdZXvVhbKwLs/gC2npKF563Cp5bejyvzqyIX8RZU5VXhW4FMWkqubasOVFMqP6mb",
	"lqy9zeF/qHFNh1lkLNFl/x7UwOZFGMZkPAYONIIyscWUGN/csGnctPZr+w7Ptz2VGbPU9aF2FeiMcEa1",
	"y2yGOVG6nvBW2kc/9id9NPz7xb+GBTo4ZAmOTEyqKdWnYxr/zSggCZ9bmX9VsNjyhP5XmAhRwiJdArEe",
	"hrVQoMEymrYUfs1MqUNUIkGRf6XsXi30qxINusiVacb9ipzXVFHcmtm63PFPidOaLSodVDoCSdSfQkqG",
	"UrXHjahlQsudWkYkuWytNZvMXTCAli3/J/7uWPzVKK5aRA2uH15c+a8Tmhu1GbaVnZ8Kl1hyStcSvwd+",
	"HsDtzAateQsf9Zb3aoQ9sfu+argod6HxSHu97ZzqQiC6Jnnnfr6dI/vQywiRZjgkSKroKqpWXB+6xCDD",
	"tkcyRpIUaPhibw+d/Dy01RlRxGLzhP2deTpggHK11zmLIM55KVereXXAVslpx7nMOwKn1CD1Mmlv5/px",
	"yCMSml+AZTtKe7l6x5bM6j6hefXzPVFBIBvEa7dnvh6hJWyyU47xke3iEqwlyM/TkXFiJYSC5pRiyu5K",
	"MQZo7Oharce8r8LRtBFc1DMdlbakG5IxGvaeDztL1ur52isBP69GZRfZgbelP1sF7imyOIWv7ZhaGYHe",
	"KrWuTG3n0KxluwOusa2gYyHZSNzprqiyrQvuaVDRucRcDmzR4IGQLFubkOzNWlgbO9TjlanIVbIqZIsN",
	"bx/bezXxvV5J/8HV5GbZridEFQ6qovJ5kb3Yowf3+yKK6JSYMg4RlmUQyMYy1G8wujxGSpCqGla+guxU",
	"sSCWEN4xfmsuugQmOJqb6F0nCjBaPmGf7fX3+y+1yg2YJwR4qTK/Z9wPhs0FoOGHHy9Qpzg61DYswPEC",
	"qc6rZrf9sdqO9Bsi3YNKZhUaXiabdZL1DMwLMOfRrMtapkEDpW0CjH2936zjjrNsTBJoK9zevAxXrpHT",
	"koKmUY1+F9beDe9Df+MMHvW7/LptDFMdDW6yY5rEW/4NlTJa27eJzkZTYT3+rn0A6dfB28gX3yil90AR",
	"jUmCzHoK88Rqyx98uYV5zRfo48G42/zUPesyB6+3fp13vZnMVZTaekJ3okEQwrUNWIT/cDWSeyw81+tZ",
	"PrXw3bUwbTWXNtfJgyB7Mz68VuXOnfDo1k3eWG15GH/MOjuteFrxbrw9tOiUCUU9zv0hGcryJPGeKFm/",
	"D3YJllkukrkxRIzmxk2iZYAbEosh6pkBbKcirUslPtuJDMdHwo2h0+8s72vSNerG6BtdRqMicc5BtkXJ",
	"lRVGt5HfxIZsw6tvunuasLs30g44jTu3kRZnShJ3i3dkouGpU4l9Fd7Kg+2rsPVXX77heggXNXC1Ozr9",
	"FKPV3KLLjsQdjAY4yybcJAXoundsjovNZJxaoWcf/PYEGcX+uI9NqNUR9KLWtwzQPp/T6H9B2g8cpK10",
	"YYXoZW9QK3kf9Db4GR8+XStcm6cQZpt0Cb1gMHuhKOImLZ6a602xEzUr1enptM5tD04uTDVCq2zVTkzT",
	"kF0dwoCodEMdG+JFPruUFPWVLh5RL8OkrCnVmSKpgAemZ2BbedSqbts6bl2j3Wjkgum6SnQez108ZIM5",
	"VIaps4bmSCZ5g8ledQRjQnX2Epuy9gzGP1wtLxx2FaCBMa4099FmAd7VtKVa3Dap54Df/ZT+A//FANTK",
	"DzwoOCtCslMg/DzE7RA0auztfvrFKKi32iEI1SzDbZPXCurualovlWvbvPWKuLuauJa6rG3qZiXcXU1e",
	"S0ndNnmzhPLuD1y9IsDic9eonvE1QCoLTKwHXK0sx1cBsyzNsAGsteofn3sSTz5wlmdGjLGD/GLvvU4J",
	"P2wKHGFDWAhbrvmwoReFxazntgZ5U36zqpEXcNp5Z4Qd6TZaksB73Kae8LmZd7CZ5L0KviXXhndyMdms",
	"U4ljYZGZ6/vr+/8fAAD//yxdbCmnogAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
