# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: falahos
before:
  hooks:
    - go generate
    - go run github.com/google/go-licenses@latest check . --disallowed_types=restricted
    - go mod tidy
    - go test -race -v ./...

builds:
  - id: falahos-amd64
    binary: build/sysroot/usr/bin/falahos
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/google_drive.client_id={{.Env.GoogleID}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/onedrive.client_id={{.Env.OneDriveID}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/dropbox.app_key={{.Env.DropboxKey}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: falahos-arm64
    binary: build/sysroot/usr/bin/falahos
    # hooks:
    #   post:
    #     - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/google_drive.client_id={{.Env.GoogleID}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/onedrive.client_id={{.Env.OneDriveID}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/dropbox.app_key={{.Env.DropboxKey}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: falahos-arm-7
    binary: build/sysroot/usr/bin/falahos
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    env:
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/google_drive.client_id={{.Env.GoogleID}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/onedrive.client_id={{.Env.OneDriveID}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/dropbox.app_key={{.Env.DropboxKey}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
  - id: falahos-riscv64
    binary: build/sysroot/usr/bin/falahos
    env:
      - CC=riscv64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/google_drive.client_id={{.Env.GoogleID}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/google_drive.client_secret={{.Env.GoogleSecret}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/onedrive.client_id={{.Env.OneDriveID}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/onedrive.client_secret={{.Env.OneDriveSecret}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/dropbox.app_key={{.Env.DropboxKey}}
      - -X github.com/IceWhaleTech/Falah OS/drivers/dropbox.app_secret={{.Env.DropboxSecret}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - riscv64
  - id: falahos-migration-tool-amd64
    binary: build/sysroot/usr/bin/falahos-migration-tool
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    main: ./cmd/migration-tool
    env:
      - CC=x86_64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64
  - id: falahos-migration-tool-arm64
    binary: build/sysroot/usr/bin/falahos-migration-tool
    # hooks:
    #   post:
    #     - upx --best --lzma -v --no-progress "{{ .Path }}"
    main: ./cmd/migration-tool
    env:
      - CC=aarch64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm64
  - id: falahos-migration-tool-arm-7
    binary: build/sysroot/usr/bin/falahos-migration-tool
    hooks:
      post:
        - upx --best --lzma -v --no-progress "{{ .Path }}"
    main: ./cmd/migration-tool
    env:
      - CC=arm-linux-gnueabihf-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
  - id: falahos-migration-tool-riscv64
    binary: build/sysroot/usr/bin/falahos-migration-tool
    main: ./cmd/migration-tool
    env:
      - CC=riscv64-linux-gnu-gcc
    ldflags:
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -s
      - -w
      - -extldflags "-static"
    tags:
      - musl
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - riscv64
archives:
  - name_template:  >- 
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-v{{ .Version }}
    id: falahos
    builds:
      - falahos-amd64
      - falahos-arm64
      - falahos-arm-7
      - falahos-riscv64
    files:
      - build/**/*
  - name_template: >-
      {{ .Os }}-{{- if eq .Arch "arm" }}arm-7{{- else }}{{ .Arch }}{{- end }}-{{ .ProjectName }}-migration-tool-v{{ .Version }}
    id: falahos-migration-tool
    builds:
      - falahos-migration-tool-amd64
      - falahos-migration-tool-arm64
      - falahos-migration-tool-arm-7
      - falahos-migration-tool-riscv64
    files:
      - build/sysroot/etc/**/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
# release:
#   github:
#     owner: IceWhaleTech
#     name: Falah OS
#   draft: true
#   prerelease: auto
#   mode: replace
#   name_template: "v{{ .Version }}"
release:
  github:
    owner: IceWhaleTech
    name: Falah OS
  draft: true
  prerelease: auto
  mode: replace
  name_template: "v{{ .Version }}"
